using System.IO;
using Celestia.Data;
using UnityEditor;
using UnityEngine;

namespace Celestia.EditorTools
{
    /// <summary>
    /// Adds the three Stylized 3D Tools (hammer, pickaxe, axe) as W3 weapons that bind
    /// to keyboard digits 6, 7, 8 (slots 5, 6, 7 in the WeaponEquipment roster — the
    /// existing W2 weapons own slots 0-4 = digits 1-5).
    ///
    /// All three reuse the W2 BasicSlash ability and attack clip — they're melee weapons
    /// that swing the same animation; what differentiates them at gameplay level is
    /// their <see cref="WeaponDefinitionSO.toolKind"/>, which world nodes (e.g.
    /// RockMineable) consult to gate damage.
    ///
    /// Idempotent. First-run sets the right-hand grip transform; subsequent runs leave
    /// the artist's tuning intact (mirroring W2_WeaponBuilder.EnsureWeapon).
    /// </summary>
    public static class W3_WeaponBuilder
    {
        private const string DIR_WEAPONS = "Assets/_Project/ScriptableObjects/Weapons";

        public const string PATH_HAMMER  = DIR_WEAPONS + "/Weapon_Hammer.asset";
        public const string PATH_PICKAXE = DIR_WEAPONS + "/Weapon_Pickaxe.asset";
        public const string PATH_W3_AXE  = DIR_WEAPONS + "/Weapon_AxeTool.asset";

        // Demo branch: primitive stand-ins replace the licensed Stylized 3D Tools pack.
        // Generated by Demo_PrimitiveAssets — run "Celestia → Demo → 1. Build Primitive
        // Source Assets" before this builder.
        private const string PREFAB_HAMMER  = Demo_PrimitiveAssets.SRC_HAMMER;
        private const string PREFAB_PICKAXE = Demo_PrimitiveAssets.SRC_PICKAXE;
        private const string PREFAB_AXE     = Demo_PrimitiveAssets.SRC_AXETOOL;

        // Source .obj models — the Stylized 3D Tools .objs no longer exist on the demo
        // branch. EnsureBakedAxisConversion no-ops when the model is missing (its
        // AssetImporter.GetAtPath returns null), so these empty paths are harmless;
        // the primitive prefabs above are already Y-up correct.
        private const string MODEL_HAMMER  = "";
        private const string MODEL_PICKAXE = "";
        private const string MODEL_AXE     = "";

        private const string PATH_SLASH_AB = "Assets/_Project/ScriptableObjects/Abilities/Ability_PhantomArcher_BasicSlash.asset";

        // Same right-hand grip defaults as the W2 melee weapons — Stylized 3D Tools meshes
        // align with the Mixamo grip the same way Blink's RPG weapons do, so artists can
        // tweak from a known-good starting point.
        private static readonly Vector3 RIGHTHAND_POS   = new(0f, 0.05f, 0.02f);
        private static readonly Vector3 RIGHTHAND_EULER = new(90f, -90f, 0f);
        private static readonly Vector3 RIGHTHAND_SCALE = new(0.5f, 0.5f, 0.5f);

        [MenuItem("Celestia/W3/2 - Build Tool Weapons (hammer/pickaxe/axe)")]
        public static void Build()
        {
            EnsureDir(DIR_WEAPONS);

            // Bake axis conversion on the .obj models — without this they import with the
            // Blender export's Z-up rotation baked into the prefab's root transform, which
            // makes the W2-style grip Euler render the tool sideways. Same fix W2 applied
            // to the sword/shield FBXs (W2_WeaponBuilder.EnsureBakedAxisConversion).
            EnsureBakedAxisConversion(MODEL_HAMMER);
            EnsureBakedAxisConversion(MODEL_PICKAXE);
            EnsureBakedAxisConversion(MODEL_AXE);

            var slash = AssetDatabase.LoadAssetAtPath<AbilityDefinitionSO>(PATH_SLASH_AB);
            if (slash == null)
            {
                Debug.LogError($"[W3_WeaponBuilder] BasicSlash ability missing at {PATH_SLASH_AB}. Run Celestia/W2/5 first.");
                return;
            }

            var slashClip = W2_AnimatorPatcher.LoadFirstClip(W2_AnimatorPatcher.CLIP_ATTACK_PLACEHOLDER);
            if (slashClip == null) Debug.LogError("[W3_WeaponBuilder] Slash clip missing — run Celestia/W2/2 first.");

            var hammerPrefab  = AssetDatabase.LoadAssetAtPath<GameObject>(PREFAB_HAMMER);
            var pickaxePrefab = AssetDatabase.LoadAssetAtPath<GameObject>(PREFAB_PICKAXE);
            var axePrefab     = AssetDatabase.LoadAssetAtPath<GameObject>(PREFAB_AXE);
            if (hammerPrefab  == null) Debug.LogError($"[W3_WeaponBuilder] Hammer source missing at {PREFAB_HAMMER}.");
            if (pickaxePrefab == null) Debug.LogError($"[W3_WeaponBuilder] Pickaxe source missing at {PREFAB_PICKAXE}.");
            if (axePrefab     == null) Debug.LogError($"[W3_WeaponBuilder] Axe source missing at {PREFAB_AXE}.");

            var pickaxeKind = AssetDatabase.LoadAssetAtPath<ToolKindSO>(W3_AssetBuilder.TOOLKIND_PICKAXE);
            var hammerKind  = AssetDatabase.LoadAssetAtPath<ToolKindSO>(W3_AssetBuilder.TOOLKIND_HAMMER);
            var axeKind     = AssetDatabase.LoadAssetAtPath<ToolKindSO>(W3_AssetBuilder.TOOLKIND_AXE);
            if (pickaxeKind == null) Debug.LogError("[W3_WeaponBuilder] ToolKind_Pickaxe missing — run Celestia/W3/1 first.");

            EnsureWeapon(PATH_HAMMER,  "Hammer",  hammerPrefab,  slashClip, slash, hammerKind);
            EnsureWeapon(PATH_PICKAXE, "Pickaxe", pickaxePrefab, slashClip, slash, pickaxeKind);
            EnsureWeapon(PATH_W3_AXE,  "Axe (Tool)", axePrefab,  slashClip, slash, axeKind);

            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
            Debug.Log("[W3_WeaponBuilder] Hammer / Pickaxe / Axe weapons built. " +
                      "Pickaxe carries the Pickaxe tool kind — required to mine rocks. " +
                      "Tune grip transforms by selecting each Weapon_*.asset → Inspector → 'Preview / Refresh' " +
                      "(same workflow as the W2 sword/axe).");
        }

        /// <summary>
        /// Tells the ModelImporter to bake the source's axis-conversion into the mesh data
        /// instead of leaving it as a rotation on the prefab's root. Mirrors
        /// W2_WeaponBuilder.EnsureBakedAxisConversion — kept private here to avoid coupling
        /// W3 to W2's editor-internals more than necessary.
        /// </summary>
        private static void EnsureBakedAxisConversion(string modelPath)
        {
            var importer = AssetImporter.GetAtPath(modelPath) as ModelImporter;
            if (importer == null) return;
            if (!importer.bakeAxisConversion)
            {
                importer.bakeAxisConversion = true;
                importer.SaveAndReimport();
            }
        }

        private static void EnsureWeapon(
            string path, string display, GameObject prefab,
            AnimationClip attackClip, AbilityDefinitionSO ability, ToolKindSO toolKind)
        {
            var w = AssetDatabase.LoadAssetAtPath<WeaponDefinitionSO>(path);
            bool firstRun = w == null;
            if (firstRun)
            {
                w = ScriptableObject.CreateInstance<WeaponDefinitionSO>();
                AssetDatabase.CreateAsset(w, path);
            }

            w.displayName = display;
            w.mainPrefab  = prefab;
            w.mainHand    = HumanBodyBones.RightHand;

            if (firstRun)
            {
                w.mainLocalPos   = RIGHTHAND_POS;
                w.mainLocalEuler = RIGHTHAND_EULER;
                w.mainLocalScale = RIGHTHAND_SCALE;
            }

            w.attackClip = attackClip;
            w.ability    = ability;
            w.toolKind   = toolKind;

            EditorUtility.SetDirty(w);
        }

        private static void EnsureDir(string path)
        {
            if (!Directory.Exists(path)) Directory.CreateDirectory(path);
        }
    }
}
